name: coding-club
channels:
  - damianavila82
  - conda-forge
  - hanslovsky
dependencies:
  - python
  - numpy
  - cython
  - dask
  - matplotlib
  - numba
  - pandas
  - scikit-image
  - scikit-learn
  - scipy
  - tifffile
  - bokeh
  - rise
  - scijava-jupyter-kernel
  - imglib2-imglyb
